---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/cosign version
    register: cosign_test_output
  - name: cosign version
    debug:
      msg: '{{ cosign_test_output.stdout }}'
