---
- name: Testing andrewrothstein.cosign
  hosts: all
  tasks:
    - name: Installing andrewrothstein.cosign
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'cosign version'
      ansible.builtin.command: /usr/local/bin/cosign version
      changed_when: false
      register: cosign_test_output
    - name: Output of 'cosign version'
      ansible.builtin.debug:
        msg: '{{ cosign_test_output.stdout }}'
