---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ cosign_url }} to {{ cosign_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ cosign_url }}'
    dest: '{{ cosign_exe }}'
    checksum: '{{ cosign_checksum }}'
    mode: '755'
- name: Linking {{ cosign_link }} to {{ cosign_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ cosign_exe }}'
    dest: '{{ cosign_link }}'
    state: link
